### PR TITLE
Update CAPS page with new content

### PR DESCRIPTION
**Pull request by nanniu**
Please update https://www.sigsoft.org/resources/caps.html with the content shown in this new file. Thanks @raux !

### CODE REVIEW

**Comment by raux** [comment]
@nanniu I have merged the new file, but I am confused with how you want me to merge this new file. Do you want me to replace the caps.html? Do you want a link to this new file?

cheers,

Raula

**Comment by nanniu** [comment]
Hi @raux Please replace the caps.html with the new content.

Thanks,
Nan

**Comment by raux** [comment]
@nanniu please verify that the information is correct.
https://www.sigsoft.org/resources/caps.html

Cheers,

Raula

**Comment by nanniu** [comment]
It looks good @raux Thank you so much!

**Pull request merged**
