### PR TITLE
Update execcomm.html with new members

### PR DESCRIPTION
**Pull request by CaptainEmerson**

### CODE REVIEW

**Comment by raux** [comment]
Let me know if you want this merged or for access for someone to merge it.

Raula

**Comment by CaptainEmerson** [comment]
Thanks, Raula! I'm just waiting on Marsha to confirm.

**Review by marsha-chechik — APPROVED** [review]

**Review by marsha-chechik — APPROVED** [review]

**Comment by raux** [comment]
Actually this is the old sigsoft website.

**Comment by raux** [comment]
Note that this repository is now deprecated.

Please use the https://github.com/acmsigsoft/acmsigsoft.github.io for updates to the https://www2.sigsoft.org/ website.

**Pull request merged**
